### ISSUE TITLE
changes in attributes

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/dive-backend#17]
**Trivialname**
- [x] Aufteilung in zwei Felder: "Angezeigter Trivialname" & "Liste alternativer Trivialnamen" (Angezeigter Trivialname erscheint dann im Header)

**Wissenswertes**
- [x] Ergänzen des neuen Abschnitts; Inhalt des Abschnitts ist eine Freitextbox

**Allgemein**
- [x] Ergänzen der Übersetzung "Ground" zu "Untergrund"

**Blätter**
- [x] Umbenennen der Eigenschaft "Blattspreite gesamt" zu "Aufteilung der Blattspreite"
- [x] Umbenennen der Eigenschaft "Spreiten/Blättchen" zu "Spreiten-/Blättchenrand"
- [x] Umbenennen der Eigenschaft "Oberflächenbeschaffenheit" zu Blattoberfläche (klare Abrenzung von Stichpunkt "Beschaffenheit")
- [x] Eigenschaft "Spreitengrund" ist zweimal vorhanden
* Änderung des zweiten "Spreitengrund" (abgerundet, gestutzt,etc.) zu Spreitenspitze
* Tippfehler bei gestutzt (Liste zum zweiten "Spreitengrund [eigentlich Spreitenspitze]")

**Keim** 
- [x] Umbenennen des Abschnittes: "Keim" wird zu "Spross"
- [x] Eigenschaft "Stellung" ist zweimal vorhanden:
* Erste Bezeichnung "Stellung" (aufrecht, etc.) ändern zu "Wuchsorientierung"
* Zweite Bezeichnung "Stellung" (stielrund, etc.) ändern zu zu "Querschnitt"
- [x] Umbenennen der Eigenschaft "Oberflächenbeschaffenheit" zu "Sprossoberfläche" (konsistent mit Blätterbezeichnung)

**Blüten**

- [x] Eigenschaft "Blütenstandstyp" ist dreimal vorhanden:
* Erste Bezeichnung "Blütenstandtyp" zu "Blütenstandsform"
* Zweite Bezeichnung "Blütenstandstyp" (ganz/ungeteilt,etc.) zu "Tragblattspreite";
Drop-down Menü ergänzen um Punkt "nicht vorhanden"
* Dritte Bezeichnung "Blütenstandstyp" (doppelte Blütenhülle (Kalyx + Corolla), etc.) zu "Blütenhülle"
- [x] Umbenennen der Eigenschaft "Farbe" zu "Kronblattfarbe"
- [x] Umbenennen der Eigenschaft "Frucht Ständigkeit" zu "Ständigkeit des Fruchtknotens"
- [x] Umbenennen der Eigenschaft "Blütig" zu "Blütigkeit des Ährchens"
- [x] Umbenennen der Eigenschaft "Ähren pro Ährchen" zu "Ährchen pro Ähre"
- [x] Umbenennen der Eigenschaft "Anordnung" zu "Anordnung der Ährchen"
- [x] Umbenennen der Eigenschaft "Ährchen pro Absatz" zu "Ährchen pro Absatz der Ährenachse"

**Comment by mgrethlein** [comment]
"Spreitengrund" ist zweimal vorhanden
- Zweite "Spreitengrund" (abgerundet, gestutzt,etc.) zu Spreitenspitze
- Tippfehler bei gestutzt (Liste zum zweiten "Spreitengrund [eigentlich Spreitenspitze]")

**Comment by chgad** [comment]
> Wissenswertes

Ergänzen des neuen Abschnitts; Inhalt des Abschnitts ist eine Freitextbox

Was ist Abschnitt gemeint?

**Comment by sheepyhollow** [comment]
Ein neuer Bereich im Steckbrief, der unter den Bildern als erstes angezeigt wird. Abschnitt meint vmtl., dass es ein ausklappbares Content Item ist wie Blätter, Blüte etc. Aber es enthält (iirc) nur ein Textfeld. Sollte `required` sein. Ist das erste, was man vom Steckbrief liest.

**Comment by sheepyhollow** [comment]
Ich glaube, es gehört nach `Pflanze` und ist kein eigenes Objekt.

**Comment by chgad** [comment]
Das was du als "Abschnitte" bezeichnet hat nicht direkt etwas mit dem Backend zu tun. allerdings: 
Ich vermute, dass das Frobtend doe Abschnitte aus Objekten erzeugt. Also aus einer Daten Struktur wie
    {
        "leaf": { ...},
        "name": "my name"
    }

Wird ein Abschnitt Blatt und eine Zeile ohne Abschnitt.

**Comment by mgrethlein** [comment]
Als Abschnitt habe ich das bezeichnet, was in django als einzelner Bestandteil des Steckbriefes ausgefüllt werden kann, bzw. wenn man eine neue Pflanze anlegt eine Überschrift besitzt. In der App wird das dann als ausklappbarer Teil dargestellt.

**Comment by sheepyhollow** [comment]
> Das was du als "Abschnitte" bezeichnet hat nicht direkt etwas mit dem Backend zu tun.

Klar, das ist aus Frontendsicht (ch hatte gestern noch etwas missverstanden).
@mgrethlein - es ist aber schon ein erforderliches Feld und nur ein Textfeld, richtig? Dann wäre es doch als Textfeld direkt im Plant-Model richtig aufgehoben (und das recht weit oben im Admin-Panel).

**Comment by mgrethlein** [comment]
Ein erforderliches Textfeld, genau. 
Im Frontend soll es dann wie von @sheepyhollow beschrieben immer direkt unter dem Bild angezeigt werden, ohne es zuerst ausklappen zu müssen.

**Comment by chgad** [comment]
Gut damit können wir arbeiten.
