### ISSUE TITLE
Steckbriefe Pflanzen "false" angezeigt im Steckbrief

### ISSUE THREAD

**Issue by IH0815** [zentrumnawi/dive-backend#31]
> Im Backend gibt es die Möglichkeit, im Pflanzensteckbrief unter "Blättter" einen Haken zu setzen, bei "Die Anordnung ist buchtig". Setzt man ihn nicht, sollte dieses Merkmal im Steckbrief nicht auftauchen. Es erscheint aber "Die Anordnung ist buchtig", gegeben mit "false" im Steckbrief.

**Comment by chgad** [comment]
Das ist mir auch letztens aufgefallen, verwandt mit #32.
