### ISSUE TITLE
Zeigerzahlen im Steckbrief

### ISSUE THREAD

**Issue by IH0815** [zentrumnawi/dive-backend#33]
Hallo,

wir haben im Conent-Meeting bereits darüber gesprochen, hier kommt wie versprochen die genaue Idee: Letzlich soll im Steckrief eine Kategorie erscheinen, die "Zeigerzahlen" heißt. Das können maximal 5 Zahlen sein: die Lichtzahl, Temperaturzahl, Feuchtezahl, Reaktionszahl und Stickstoffzahl. Jeder Pflanze soll also ein Wert pro Zahl zugewiesen werden können. Dafür wären im Backend 5 Dropdownmenüs erforderlich, je eines pro Zahl. In diesen Menüs kann man dann auswählen, welcher Wert der einzelnen Pflanze zugewiesen werden soll. 

Bitte richte es so ein, dass eine Zahl, der von mir o. Martin _kein_ Wert zugewiesen wurde, im Steckbrief nicht erscheint. Auf der anderen Seite ist aber eine Kategorie "nicht angegeben" notwenidig, falls die Zahl als nicht definierbar im Bestimmungsbuch geführt wird --> mehr dazu aber in der Liste der Zahlen (bspw. L? - ungeklärtes Verhalten). 

Einige Zahlen sind im Bestimmungsbuch nicht genau definiert und daher _zusätzlich_ mit einem "?" gekennzeichnet. Wenn es geht, bitte so einrichten, dass pro Zahlentyp (also bspw. Feuchtezahl) ein "(?)" angegeben werden kann, welches mit angezeigt wird (bspw. _F7 - Feuchtezeiger (?)_ ). Dabei sollte dann folgende Definition erscheinen, am Besten irgendwo am Schluss: "Zahl mit (?) = unsichere Einstufung" Die Definition sollte nur einmal erscheinen, selbst wenn bei mehreren Zahlen ein (?) zusätzlich ausgewählt wurde. Falls das zu umständlich ist, die Definition nur einmal erscheinen zu lassen, tut es auch ein zusätzliches Anwählfelt, das bestimmt, dass die Definition des Fragezeichens angezeigt wird, das wir dann anklicken können. Dieses Fragezeichen ist verschieden von dem Fragezeichen, das anzeigt, dass es dazu einfach keine Daten gibt (s. Liste & 2. Beispiel). 
Dasselbe gilt für das "~" nur bei der Feuchtezahl, dieses bitte mit der zusätzlichen Erklärung anzeigen: "Zeiger für starken Wechsel". (s. 2. Beispiel)

Ob wir im Backend bspw. anwählen können "F1" und im Steckbrief erscheint "F1 - Starktrockniszeiger" oder ob auch im Dropdownmenü schon "F1 - Starktrockniszeiger" steht, ist völlig egal, wichtig ist, dass im Frontent sowohl die Zahl als auch die Definition angegeben sind. Die Studenten sollen die Zahl mit der Definition verbinden. 

Falls noch etwas unklar sein sollte, melde dich bitte^^

So in etwa sollte es im Frontend dann aussehen (die Zuweisungen habe ich gerade erfunden): 

_Beispielpflanze Kerstin Hartmann:_ 
**Zeigerzahlen**
Lichtzahl: L1 - Tiefschattenpflanze
Temperaturzahl: T5 - Mäßigwärmezeiger
Feuchtezahl: F7 - Feuchtezeiger
Reaktionszahl: R6 - zwischen Mäßigsäurezeiger und Schwachsäure- bis Schwachbasenzeiger
Stickstoffzahl/Nährstoffzahl: N3 - häufig auf stickstoffarmen Standorten

_Beispielpflanze Johanna Mustermann:_ (die ich gerade erfunden habe)
**Zeigerzahlen**
Lichtzahl: L1 - Tiefschattenpflanze
Temperaturzahl: T? - ungeklärtes Verhalten
Feuchtezahl: F7~ - Feuchtezeiger
Reaktionszahl: R6 - zwischen Mäßigsäurezeiger und Schwachsäure- bis Schwachbasenzeiger
Stickstoffzahl/Nährstoffzahl: N3 - häufig auf stickstoffarmen Standorten (?)

~ Zeiger für starken Wechsel
Zahl mit (?) = unsichere Einstufung

-------------------------------------------------------------------------------------------------------

_Hier die Liste der Zahlen, die in den entsprechenden Dropdownmenüs anwählbar sein sollen:_

**Lichtzahl**
L1 - Tiefschattenpflanze
L2 - zwischen Tiefschatten- und Schattenpflanze
L3 - Schattenpflanze
L4 - zwischen Schatten- und Halbschattenpflanze
L5 - Halbschattenpflanze
L6 - zwischen Halbschatten- und Halblichtpflanze
L7 - Halblichtpflanze
L8 - Lichtpflanze
L9 - Vollichtpflanze
Lx - indifferentes Verhalten
L? - ungeklärtes Verhalten

**Temperaturzahl**
T1 - Kältezeiger
T2 - zwischen Kälte- und Kühlezeiger
T3 - Kühlezeiger
T4 - zwischen Kühle- und Mäßigwärmezeiger
T5 - Mäßigwärmezeiger
T6 - zwischen Mäßigwärme- und Wärmezeiger
T7 - Wärmezeiger
T8 - zwischen Wärme- und extremer Wärmezeiger
T9 - extremer Wärmezeiger
Tx - indifferentes Verhalten
T? - ungeklärtes Verhalten

**Feuchtezahl**
F1 - Starktrockniszeiger
F2 - zwischen Starktrocknis- und Trockniszeiger
F3 - Trockniszeiger
F4 - zwischen Trocknis- und Frischezeiger
F5 - Frischezeiger
F6 - zwischen Frische- und Feuchtezeiger
F7 - Feuchtezeiger
F8 - zwischen Feuchte- und Nässezeiger
F9 - Nässezeiger
F10 - Wechselwasserzeiger
F11 - Wasserpflanze
F12 - Unterwasserpflanze
Fx - indifferentes Verhalten
F? - ungeklärtes Verhalten
F= - Überschwemmungszeiger

**Reaktionszahl**
R1 - Starksäurezeiger
R2 - zwischen Starksäure- und Säurezeiger
R3 - Säurezeiger
R4 - zwischen Säure- und Mäßigsäurezeiger
R5 - Mäßigsäurezeiger
R6 - zwischen Mäßigsäurezeiger und Schwachsäure- bis Schwachbasenzeiger
R7 - Schwachsäure- bis Schwachbasenzeiger
R8 - zwischen Schwachsäure- bis Schwachbasen- und Basen- und Kalkzeiger
R9 - Basen- und Kalkzeiger
Rx - indifferentes Verhalten
R? - ungeklärtes Verhalten

**Stickstoff/Nährstoffzahl**
N1 - stickstoffärmste Stanorte anzeigend
N2 - zwischen stickstoffärmsten und -armen Standorten
N3 - häufig auf stickstoffarmen Standorten
N4 - zwischen: häufig auf stickstoffarmen und mäßig -reichen Standorten
N5 - mäßig stickstoffreiche Standorte
N6 - zwischen: mäßig und häufig anstickstoffreichen Standorten
N7 - häufig an stickstoffreichen Standorten
N8 - zwischen: häufig an und übermäßig stickstoffreichen Stanorten
N9 - übermäßig stickstoffreiche Standorte
Nx - indifferentes Verhalten
N? - ungeklärtes Verhalten

**Comment by chgad** [comment]
- [ ] implementiere `CharField()` Lichtzahl

- [ ] implementiere `CharField()` Temperaturzahl

- [ ] implementiere `CharField()` Feuchtezahl

- [ ] implementiere `CharField()` Reaktionszahl

- [ ] implementiere `CharField()` Stickstoff/Nährstoffzahl

**Comment by chgad** [comment]
> ~ Zeiger für starken Wechsel
> Zahl mit (?) = unsichere Einstufung

wird in  #44 abgehakt
