### ISSUE TITLE
Änderungen Kategorie "Allgemein"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#38]
_**Für die Reihenfolge und Anordnung im Admin-Interface bitte #40  beachten**_

### **Wissenswertes** 
- [x] Umbenennen in „Kurzbeschreibung“

### **Untergrund**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden
- [x] Entfernen der Optionen “nährstoffreich & nährstoffarm”

### **Blütezeit**
- [x] Verschieben in Kategorie „Blüte“;
- [x] Tooltip hinzufügen: „Format: (Januar) Februar bis März“

### **Primärwurzel**
- [x] Verschieben in Kategorie „Spross und Wurzel“ (NEU);

###  **Wurzelknollen**
- [x] Löschen

###  **Steckbrief-Ebene**
- [x] Verwendet zur Erstellung der neuen Kategorie „Taxonomie“ im Frontend

###  **NEU Lebensform**
- Dropdown
- Einträge:
Phanerophyt; Chamaephyt; Hemikryptophyt; Kryptophyt; Therophyt
- [x] Erstellen

 ### **NEU Wuchsform**
- Dropdown
- Einträge:
Baum; Strauch; Strauchbaum; Zwergstrauch; Liane; Kletterpflanze; Halbstrauch; Spalierstrauch; krautiger Chemaephyt; Geophyt; Helophyt (Sumpfpflanze); Hydrophyt (Wasserpflanze); Tauchpflanze; Schwimmpflanze
- [x] Erstellen

### **NEU Wuchshöhe**
- Textfeld
- Tooltip: „Spannen mit Bindestrich OHNE Leerzeichen angeben, z. B. 15-25 cm”
- [x] Erstellen

### **NEU Ausbreitungsform**
- Dropdown
- Einträge:
Samenpflanze; Sporenpflanze
- [x] Verschieben aus Kategorie "Frucht"

**Comment by chgad** [comment]
Notizen zur Impementierung.

Diese Felder kommen in das Model Plant.

Feldnamen für Felder:

Lebensform --> life_form
Wuchsform --> grow_form
Wuchshöhe --> grow_height
Ausbreitungsform ---> @mgrethlein @IH0815 Das Feld ist momentan in "Frucht" angesiedelt soll es umziehen?
