### ISSUE TITLE
Änderungen Kategorie "Blatt"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#39]
_**Für die Reihenfolge und Anordnung im Admin-Interface bitte #40  beachten**_

### **Anheftung an Sprossachse**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Struktur der Blattspreite**
- [x] Löschen

### **Tiefe von Einschnitten**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden
- [x] Dropdowneinträge ergänzen: 
„gefingert; zusammengesetzt; fiederschnittig; gefiedert“

### **Anordnung der Spreite**
- [x] Umbenennen in „Gestalt der Spreite (geteiltes Blatt)“
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden
- [x] Änderung der Dropdowneinträge: 
1.	„handförmig/fingerförmig“ löschen
2.	Drei Einträge „handförmig gelappt / geteilt / geschnitten“ reduzieren auf einzelnen Eintrag „handförmig“
3.	„fiederförmig/fiedrig“ ändern zu „fiederförmig“
4.	Zwei Einträge „paarig / unpaarig gefiedert“ reduzieren auf zwei Einträge „paarig; unpaarig“
5.	Zwei Einträge „unterbrochen fiederschnittig / gefiedert“ reduzieren auf einen Eintrag „unterbrochen“
6.	„doppelt gefiedert“ ändern zu „doppelt“
7.	„mehrfach gefiedert“ ändern zu „mehrfach“
8.	Zwei Einträge „fußförmig geschnitten / zusammengesetzt“ reduzieren auf einen Eintrag „fußförmig“

### **Gestalt der Spreite**
- [x] Umbenennen in „Gestalt der Spreite (ungeteiltes Blatt)“
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Anzahl der Blättchen**
- [x] Löschen

### **Spreiten/Blättchenrand**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Blattoberfläche**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Nebenblattrand** 
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Dickfleischig**
- [x] Dropdown ändern zu „dickfleischig; nicht dickfleischig“

### **Grundblattrose**
- [x] Verschieben von Kategorie „Sprout“
- [x] Änderung zu Dropdown
- [x] Einträge:
	„Grundblattrose vorhanden; keine Grundblattrose“

### **NEU Anzahl Blätter (geteilte Blätter)**
- [x] Textfeld

### **NEU Anzahl Einschnitte**
- [x] Textfeld

### **NEU Anzahl Einschnitte (Blättchen)**
- [x] Textfeld

### **NEU Zusatz zu Einschnitten (Blättchen)**
- [x] Textfeld

### **NEU Tiefe von Einschnitten (Blättchen)**
- [x] Wie Tiefe von Einschnitten

### **NEU Anzahl Blätter (einfache Blätter)**
- [x] Textfeld

**Comment by chgad** [comment]
Notizen zur Impementierung.

Diese Felder kommen in das Model Leaf.

Feldnamen für Felder:

Anzahl Blätter (geteilte Blätter) --> cnt_split_leafs
Anzahl Einschnitte --> cnt_cuts
Anzahl Einschnitte (Blättchen) --> cnt_leaflet_cuts
Zusatz zu Einschnitten (Blättchen) --> cuts_extra
Anzahl Blätter (einfache Blätter) --> cnt_single_leafs

**Comment by suehtomit** [comment]
```
    ALTER BEGRIFF                           NEUER BEGRIFF                         |  ALTE VARIABLE         NEUE VARIABLE
 -----------------------------------------------------------------------------------------------------------------------------------
 1. Blattnerven                                                                   |  nerves            ->  veins
 2. Aufteilung der Blattspreite         ->  Spreitengliederung                    |  spr_whole         ->  division
 3. Dickfleischig                       ->  Dickfleischigkeit                     |  thick_flesh       ->  succulence
 4. Beschaffenheit                                                                |  texture
 5. Querschnitt                                                                   |  diam              ->  cross_section
 6. Anheftung an Sprossachse            ->  Anheftung (an Sprossachse)            |  att_axis          ->  attachment
 7. Stellung an Sprossachse             ->  Anordnung (an Sprossachse)            |  pos_axis          ->  arrangement
 8. Grundblattrose                      ->  Grundblattrosette                     |  rose              ->  rosette
 9. Anzahl Blätter (geteilte Blätter)   ->  Blattanzahl (zusg. Blätter)           |  cnt_split_leafs   ->  leaf_comp_num
10. Gestalt der Spreite                 ->  Spreitengestalt (unterteiltes Blatt)  |  from              ->  blade_subdiv_shape
11. Anzahl Einschnitte                  ->  Einschnittanzahl                      |  cnt_cuts          ->  incision_num
12. Tiefe von Einschnitten              ->  Einschnitttiefe                       |  dep_cuts          ->  incision_depth
13. Anzahl Einschnitte (Blättchen)      ->  Einschnittanzahl (Blättchen)          |  cnt_leaflet_cuts  ->  leaflet_incision_num
14. Zusatz zu Einschnitten (Blättchen)  ->  Einschnittzusatz (Blättchen)          |  cuts_extra        ->  leaflet_incision_add
15. Tiefe von Einschnitten (Blättchen)  ->  Einschnitttiefe (Blättchen)           |                        leaflet_incision_depth
16. Anzahl Blätter (einfache Blätter)   ->  Blattanzahl (einf. Blätter)           |  cnt_single_leafs  ->  leaf_simple_num
17. Gestalt der Spreite                 ->  Spreitengestalt (ungeteiltes Blatt)   |                        blade_undiv_shape
18. Spreiten-/Blättchenrand                                                       |  leaflets          ->  edge
19. Blattoberfläche                                                               |  sur_texture       ->  surface
20. Nebenblattrand                                                                |  side_leaf         ->  stipule_edge
21. Spreitengrund                                                                 |  sp_ground         ->  base
22. Spreitenspitze                                                                |  sp_top            ->  apex
23. Besondere Merkmale                                                            |  specialty         ->  special_features
24. Blattscheide                                                                  |  sheath
25. Anzahl der Keimblätter              ->  Keimblattanzahl                       |  cnt_germ          ->  seed_leaf_num
```

**Comment by suehtomit** [comment]
Frage von @sheepyhollow:
> Wo ich gerade die Commit-History und "Blossom.Griffel" sehe...
> Wie ist es denn mit den ganzen Bezeichnungen? Wie konsequent sind die übersetzt?

Da habe ich es mir zur Aufgabe gemacht.
