### ISSUE TITLE
Neue Anordnung der Eingabe im Admin-Interface

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#40]
Die Eingabefelder haben eine neue Ordnung bekommen:
[Django Admin Layout.xlsx](https://github.com/zentrumnawi/dive-backend/files/5611448/Django.Admin.Layout.xlsx)
Die Farbcodierung ist wie folgt:
grün: Vorhanden und unverändert
orange: Vorhanden, für Änderungen siehe entsprechende issues
rot: Neuer Eintrag

Die Felder bitte so weit es geht an dieser Vorlage orientiert anordnen, inklusive der Unterteilungen, falls möglich.

**Comment by chgad** [comment]
@suehtomit 
Wir haben uns geeinigt die Inlines "collapseable" zu machen ( Setze statische Klassenvariable `classes = ["collapse",]`).

Die genannten Kategorien können als `fieldsets` ([take me to the docks](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets)) Implementiert werden, wobei Kategorien mit jeweils nur einem Eintrag ersteinaml weg gelassen werden und so belassen werden (Achtung die Felder, die nicht in Kategoreien sind müssen in den `fieldsets` als (None, { "fields": ...}) angegeben werden.)
