### ISSUE TITLE
Änderungen Kategorie "Spross"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#41]
_**Für die Reihenfolge und Anordnung im Admin-Interface bitte #40  beachten**_

### **Kategorie "Spross"**
- [x] Umbenennen in „Spross und Wurzel“

### **Erscheinung**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Wuchsorientierung**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Dickfleischig** 
- [x] Dropdown ändern zu „dickfleischig; nicht dickfleischig“

### **Milchsaft**
- [x] Möglichkeit mehr als 3 Zeichen eingeben zu können
- [x] Tooltip: „Eingabe: kein Milchsaft, gelber Milchsaft, etc“

### **Beblätterung**
- [x] Groß/Kleinschreibung im Dropdown anpassen: „auch …; nur …“

### **Querschnitt** 
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **Sprossoberfläche**
- [x] Dropdown mit mehrfach Auswahl, ausgewählte Begriffe mit „bis“ verbinden

### **NEU Kriech und Legetriebe**
- [x] Dropdown
- [x] Einträge:
	„bildet Kriech- und Legetriebe; keine Angabe“

### **NEU Oberirdische Ausläufer**
- [x] Dropdown
- [x] Einträge:
„bildet oberirdische Ausläufer; keine Angabe“

### **NEU Besonderheiten der Wurzel**
- [x] Textfeld
- [x] Tooltip: „besondere Ausprägungen; alles Ausschreiben“

### **NEU Unterirdische Organe**
- [x] Dropdown
- [x] Einträge:
„Rhizom, Zwiebel, unterirdische Ausläufer, Innovations-Wurzelknolle, Wurzelknollen, Wurzeln“

### **Halm**
- [x] löschen

### **Horst**
- [x] löschen

**Comment by chgad** [comment]
Notizen zur Impementierung.

Diese Felder kommen in das Model Plant.

Feldnamen für Felder:

Kriech und Legetriebe --> crawl_sprout
Oberirdische Ausläufer --> speciality
Unterirdische Organe --> undergr_organ

**Comment by suehtomit** [comment]
```
   ALTER BEGRIFF                  NEUER BEGRIFF            |  ALTE VARIABLE        NEUE VARIABLE
-----------------------------------------------------------------------------------------------------
 1. Wuchsorientierung                                       |  pos              ->  orientation
 2. Erscheinung                                             |  appear           ->  appearance
 3. Dickfleischig              ->  Dickfleischigkeit        |  thick_flesh      ->  succulence
 4. Querschnitt                                             |  diam             ->  cross_section
 5. Sprossoberfläche                                        |  sur_texture      ->  surface
 6. Kriech- und Legetriebe                                  |  crawl_sprout     ->  creep_lay_shoots
 7. oberirdische Ausläufer     ->  Ausläufer (oberirdisch)  |  speciality (*?)  ->  runners
 8. Beblätterung                                            |  leafly           ->  bracts
 9. Milchsaft                                               |  milk             ->  milky_sap
10. Besonderheiten der Wurzel  ->  Besonderheiten (Wurzel)  |  (*?)             ->  root_features
11. Unterirdische Organe       ->  Organe (unterirdisch)    |  undergr_organ    ->  organs
12. Primärwurzel                                            |  primary_root
```

**Comment by suehtomit** [comment]
Vidyo-Meeting (@mgrethlein, @suehtomit ):

- Ausgabe "Sprossmorphologie" wird zusammengefasst: `[Wuchsorientierung]er, [Erscheinung]er, [Dickfleischigkeit]er Spross; [Querschnitt]er Querschnitt mit [Sprossoberfläche]er Oberfläche.`
- Ausgabe "Auswüchse": `[Kriech- und Legetriebe]; [oberirdische Ausläufer].`
- Änderungen in `ORIENTATION_CHOICES`:
```
Rankenpflanze    ->  rankenpflanzen
Windepflanze     ->  windepflanzen
Spreizklimmer    ->  spreizklimmig
Wurzelkletterer  ->  wurzelkletternd
```
- Änderung in `BRACTS_CHOICES`:
`auch über Grund  ->  auch überm Grund`
- Ausgabe "Wurzelmorphologie": `[Besonderheiten] [unterirdische Organe]; Primärwurzel [Primärwurzel].`
- Änderung in `PRIMARY_ROOT_CHOICES`:
`ersetzt durch sprossbürtige Wurzeln  ->  durch sprossbürtige Wurzeln ersetzt`
- Änderung von `root_features`:
```
root_features  ->  organ_features
verbose_name = "Besonderheiten"
help_text = "Besondere Ausprägungen der unterirdischen Organe."
```

**Comment by sheepyhollow** [comment]
> auch über Grund -> auch überm Grund
Sicher mit "überm"? Ist für schriftliches Deutsch nicht unbedingt ideal (falls es nicht ein spezielles Bio-Ding ist). 
Vielleicht eher "über dem Grund"?

**Comment by suehtomit** [comment]
Das Feld hat zwei Optionen `nur am Grund` und `auch überm Grund` aus denen wahlweise die Sätze generiert werden:
- `Nur am Grund beblättert.`
- `Auch überm Grund beblättert.`

Da es sich um knapp Sätze handelt, neigte ich zum kurzen Wort. Vermutlich auch, weil ich es im Vergleich zu "am" betrachtet habe, dass aus "an dem"  gebildet wird. `Nur an dem Grund beblättert.` wäre untypisch formuliert.

Isoliert betrachtet, empfinde ich `Auch über dem Grund beblättert.` mittlerweile passender – ändere es gleich um.
