### ISSUE TITLE
Änderungen Kategorie "Frucht"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#42]
_**Für die Reihenfolge und Anordnung im Admin-Interface bitte #40  beachten**_

### **Ausbreitungsform**
- [x] Löschen

### **Lage der Samenanlage**
- [x] Dropdowneinträge ändern zu: „Fruchtknoten (Angiospermen); Zapfenschuppe (Gymnospermen)“
- [x] Eintrag „Sprossachse“ löschen

### **Fruchttyp**
- [x] Eintrag „Apfelfrucht“ ergänzen

### **Form**
- [x] Umbenennen zu „Form der Samen“
- [x] Tooltip: „Alles ausschreiben“

### **Beflügelung**
- [x] Tooltip: „Alles ausschreiben“

### **Beflügelung Besonderheit**
- [x] Tooltip: „Alles ausschreiben“

### **NEU Form der Frucht**
- [x] Textfeld

**Comment by chgad** [comment]
Notizen zur Impementierung.

Diese Felder kommen in das Model Plant.

Feldnamen für Felder:

Form der Frucht ---> form

**Comment by suehtomit** [comment]
```
    ALTER BEGRIFF                 NEUER BEGRIFF               |  ALTE VARIABLE   NEUE VARIABLE
 -------------------------------------------------------------------------------------------------
 1. From der Frucht           ->  Fruchtform                  |  form (?)    ->  fruit_form
 2. Fruchttyp                                                 |  type        ->  fruit_type
 3. Lage der Samenanlage      ->  Samenanlage (Lage)          |  pos         ->  ovule_pos
 4. Samenzahl                 ->  Samenanzahl                 |  cnt         ->  seed_num
 5. Form der Samen            ->  Samenform                   |  form (?)    ->  seed_form
 6. Beflügelung                                               |  wings       ->  winging
 7. Beflügelung Besonderheit  ->  Besonderheit (Beflügelung)  |  wings_spec  ->  winging_feature
```
