### ISSUE TITLE
Änderungen Kategorie "Blüte"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#43]
_**Für die Reihenfolge und Anordnung im Admin-Interface bitte #40  beachten**_

### **Blüten pro Blütenstand**
- [x] Tooltip: „ausgegeben als „mit [Eintrag] Blüten

### **Symmetrie**
- [x] Einträge bearbeiten:
	Nur ersten Begriff je Eintrag behalten (radiärsymmetrisch; disymmetritsch; etc)

### **Blütenhülle**
- [x] Eintrag ergänzen:
	„Röhrenblüte“

### **Kelchblätter**
- [x] Löschen

### **Verwachsungstyp**
- [x] Zahlenwerte entfernen, Einträge auf je ein „-zähnig“ etc. reduzieren
- [x] Kategorie duplizieren; vgl. Layout #40 

### **Kronblattfarbe**
- [x] Umbenennen zu „Farbe & Gestalt der Kronblätter“

### **Kronblatt Platte**
- [x] Umbenennen in Länge des Kronblattes (Platte)
- [x] Tooltip: „Länge, Einheit cm“

### **Kronblatt Unterlippe**
- [x] Zahlenwerte entfernen, Einträge auf je ein „-zähnig“ etc. reduzieren

### **Staubfadenröhre**
- [x] Umbenennen in „Verwachsungstyp der Staubblätter“
- [x] Dropdown; Einträge:
	„Staubfadenröhre; verwachsen mir Kronblättern“

### **Fruchtknoten Anzahl**
- [x] Umbenennen in „Fruchtblätter Anzahl“

### **Ständigkeit des Fruchtknotens**
- [x] Einträge kürzen auf deutsche Begriffe („hypogyn/oberständig“ zu „oberständig“ etc.)

### **Bau des Gynoeceums**
- [x] Umbenennen in „Verwachsungstyp der Fruchtblätter“

### **Narben pro Griffel**
- [x] Tooltip: „Zahlenwert eingeben; Angezeigt als „Griffel mit X/x-y Narben“
 
### **Ständigkeit des Griffels**
- [x] Dropdowneinträge aus „Ständigkeit des Griffels ist sub-“ hinzufügen

### **Ständigkeit des Griffels ist sub**
- [x] Einträge verschieben nach „Ständigkeit des Griffels“, dann löschen

### **Sporn**
- [x] Umbenennen in „Form der verwachsenblättrigen Blütenhülle

### **Griffelpolster**
- [x] Tooltip: „Alles ausschreiben“

### **Schlauch**
- [x] Löschen

### **NEU Blütezeit**
- [x] Eintrag aus Kategorie „Allgemein“ hierher verschieben
- [x] Tooltip hinzufügen: „Format: (Januar) Februar bis März“

### **NEU Anzahl der Blütenstände**
- [x] Textfeld
- [x] Tooltip: „Zahlenwert eintragen“

### **NEU Blütendurchmesser**
- [x] Textfeld
- [x] Tooltip: „Einheit: cm“

### **NEU Farbe/ Gestalt der Kelchblätter**
- [x] Textfeld

### **NEU Zahlenwert der Verwachsung**
- [x] Textfeld

### **NEU Verwachsungstyp**
Bereits vorhanden, Kopie benötigt für weitere Blätter
- [x] Dropdown; Einträge:
	„freiblättrig; verwachsenblättrig; -zähnig; -lappig; -spaltig; -teilig; zweilippig“

### **NEU Verwachsung der Kelchblätter**
- [x] Textfeld

### **NEU Zusatz Verwachsungstyp**
- [x] Textfeld

**Comment by chgad** [comment]
Notizen zur Impementierung.

Gerne die neuen Felder zu passenden, verhondenen im Model gruppieren.

Diese Felder kommen in das Model Blossom.

Feldnamen für Felder:

Blütezeit --> bloom_time
Anzahl der Blütenstände --> stand_ctn
Blütendurchmesser --> diameter
Farbe/ Gestalt der Kelchblätter --> chalice_color
Zahlenwert der Verwachsung --> ver_cnt (Verwachsung habe ich schon mal mit ver abgekürzt)
Verwachsungstyp --> ver_type
Verwachsung der Kelchblätter --> ver_chalice
Zusatz Verwachsungstyp --> ver_addition

**Comment by suehtomit** [comment]
```
   ALTER BEGRIFF                                  NEUER BEGRIFF                  |  ALTE VARIABLE      NEUE VARIABLE
------------------------------------------------------------------------------------------------------------------------------
 1. + Blütezeit                                                                   |  bloom_time     ->  season # Erledigt #51
 2. + Anzahl der Blütenstände                  ->  Blütenstandsanzahl             |  stand_ctn      ->  inflorescence_num
 3. Blütenstandsform                           ->  Blütenstandstyp                |  type           ->  inflorescence_type
 4. Blüten pro Blütenstand                     ->  Blütenanzahl (pro Stand)       |  bl_cnt         ->  blossom_num
 5. Zähligkeit                                                                    |  cnt            ->  merosity
 6. Symmetrie                                                                     |  sym            ->  symmetry
 7. Blütenhülle                                                                   |  hull           ->  perianth
 8. Form der verwachsenblättrigen Blütenhülle  ->  Blütenhüllenform               |  spec_sporn     ->  perianth_form
 9. Tragblattspreite                                                              |  parting        ->  bract_blade
10. + Blütendurchmesser                        ->  Durchmesser                    |  diameter

11. + Farbe & Gestalt der Kelchblätter         ->  Farbe/Gestalt (Kelchblatt)     |  chalice_color  ->  sepal_color_form
12. + Zahlenwert der Verwachsung # In Verwachsungstyp-Widget implementiert        |  ver_cnt
13. Verwachsungstyp                            ->  Verwachsungstyp (Kelchblatt)   |  ch_type        ->  sepal_connation_type
14. + Verwachsung der Kelchblätter             ->  Verwachsung (Kelchblatt)       |  ver_chalice    ->  sepal_connation
15. Außenkelch                                                                    |  sec_out        ->  epicalyx

16. Länge des Kronblattes (Platte)             ->  Kronblattlänge (Platte)        |  crown_plate    ->  petal_len
17. Farbe & Gestalt der Kronblätter            ->  Farbe/Gestalt (Kronblatt)      |  crown_color    ->  petal_color_form
18. + Zahlenwert der Verwachsung # In Verwachsungstyp-Widget implementiert        |
19. + Verwachsungstyp                          ->  Verwachsungstyp (Kronblatt)    |  crown_lower    ->  petal_connation_type
20. Verwachsung der Kronblätter                ->  Verwachsung (Kronblatt)        |  crown_ver      ->  petal_connation
21. Honigdrüsen / Nektarien                    ->  Nektarium/Honigdrüse           |  spec_hon       ->  nectary

22. Staubblatt Anzahl                          ->  Staubblattanzahl               |  dust_cnt       ->  stamen_num
23. Staubblatt Länge                           ->  Staubblattlänge                |  dust_len       ->  stamen_len
24. Staubblatt Farbe                           ->  Staubblattfarbe                |  dust_color     ->  stamen_color
25. Verwachsungstyp der Staubblätter           ->  Verwachsungstyp (Staubblatt)   |  dust_pipe      ->  stamen_connation_type
26. + Zusatz Verwachsungstyp                   ->  Verwachsungstypzusatz          |                 ->  stamen_connation_type_add

27. Fruchtblätter Anzahl                       ->  Fruchtblattanzahl              |  fruit_cnt      ->  carpel_num
28. Verwachsungstyp der Fruchtblätter          ->  Verwachsungstyp (Fruchtblatt)  |  fruit_build    ->  carpel_connation_type
29. Ständigkeit des Fruchtknotens              ->  Fruchtknotenstellung           |  fruit_stand    ->  ovary_pos
30. Ständigkeit des Griffels                   ->  Griffelstellung                |  griffel_stand  ->  pistil_pos
31. Narben pro Griffel                         ->  Narbenanzahl (pro Griffel)     |  fruit_scar     ->  stigma_num
32. Griffelpolster                                                                |  spec_pol       ->  stylopodium
```

**Comment by suehtomit** [comment]
Vidyo-Meeting 12.04.2021 (@IH0815, @mgrethlein, @suehtomit ):

- [ ] Felder entsprechend Auflistung benennen
  - [ ] Änderung bei 8.: `Blütenhüllenform`   ->  `Blütenhüllenform (verwachsenblättrig)`
  - [ ] Änderung bei 24.: `Staubblattfarbe`  ->  `Farbe/Gestalt (Staubblatt)`

- [ ] **Blütezeit**: Textfeld zu einem Feld umgestalten, was eine Auswahl der Monatsnamen ermöglicht und diese entsprechend der Vorgabe `(Monat_1) Monat_2 bis Monat_3 (Monat_4)` zusammensetzt

- [ ] **Blütezeit** (Ausgabe): Nur Feldwert ohne zusätzliche Kategoriebezeichnung und Satzstruktur

- [ ] **Blütenstandsanzahl**: IntegerRangeCharField mit 1-(100 = ∞), Tooltip verwerfen

- [ ] **Blütenstandstyp**: Option `einzeln`  ->  `Einzelblüte`

- [ ] **Blütenanzahl (pro Stand)**: IntegerRangeCharField mit 1-(100 = ∞), Tooltip verwerfen

- [ ] **Zähligkeit**: Optionen: `-, 2, 3, 4, 5, 6, 7, 8, viel`

- [ ] **Zähligkeit + Symmetrie + Blütenhülle** im Admin-Interface gruppieren

- [ ] **Tragblattspreite**: MultipleChoiceField, Optionen: `BLADE_SUBDIV_SHAPE_CHOICES + BLADE_UNDIV_SHAPE_CHOICES + "nicht vorhanden"`, Auswahl (max 2) mit "bis" verbinden

- [ ] **Durchmesser + Kronblattlänge (Platte) + Staubblattlänge**: (Integer)RangeCharField mit 0,1-100, Widgetzusatz `"cm"`, Tooltip verwerfen
  - [ ] `IntegerRangeCharField`  ->  `NumberRangeCharField`  erweitern

- [ ] **Durchmesser** (Ausgabe): Nur Feldwert ohne zusätzliche Kategoriebezeichnung und Satzstruktur, `"cm"` anhängen

- [ ] **Kelchblattanzahl + Kronblattanzahl + Staubblattanzahl + Fruchtblattanzahl**: IntegerRangeCharField mit 1-(11 = ∞)
  - [ ] **Kelchblattanzahl** (CharField) erstellen
  - [ ] **Kronblattanzahl** (CharField) erstellen

- [ ] **Kelchblattanzahl + Farbe/Gestalt (Kelchblatt)** im Admin-Interface gruppieren

- [ ] **Zahlenwert der Verwachsung + Verwachsungstyp (Kelchblatt + Kronblatt)**: Zu einem Feld (Verwachsungstyp) zusammenfassen
  - [ ] `ConnationTypeField` erstellen
  - [ ] Optionen Zahlenwert: `-, 2, 3, 4, 5`
  - [ ] Optionen Verwachsungstyp: `---------, -zähnig, -lappig, -spaltig, -teilig, freiblättrig, verwachsenblättrig, zweilippig`
  - [ ] Zahlenwert bei Verwachsungsopitonen mit Bindestich erforderlich, bei den anderen Optionen Zahlenwerte verwerfen

- [ ] **Verwachsung (Kelchblatt)**: Dropdown, Optionen wie bei Verwachsung (Kronblatt)

- [ ] **Verwachsungstyp (Kelchblatt) + Verwachsung (Kelchblatt)** im Admin-Interface gruppieren

- [ ] Kelchblatt Ausgabe: "[Kelchblattanzahl] [Farbe/Gestalt (Kelchblatt)] `Kelchblätter,` [Verwachsungstyp (Kelchblatt)] [Verwachsung (Kelchblatt)]`;` [Außenkelch]`.`"

- [ ] **Kronblattanzahl + Kronblattlänge + Farbe/Gestalt (Kronblatt)** im Admin-Interface gruppieren

- [ ] **Verwachsungstyp (Kronblatt) + Verwachsung (Kronblatt)** im Admin-Interface gruppieren

- [ ] Kronblatt Ausgabe: "[Kronblattanzahl] [Kronblattlänge (Platte)] `cm lange,` [Farbe/Gestalt (Kronblatt)] `Kronblätter,` [Verwachsungstyp (Kronblatt)] [Verwachsung (Kronblatt)]`;` [Nektarium/Honigdrüse]`.`"

- [ ] Feld Ausstülpung der Unterlippe löschen

- [ ] Neue Kategorie "Perigonblatt" erstellen:
  - [ ] Felder analog zu Kelch-/Kronblatt: **Perigonblattanzahl**, **Farbe/Gestalt (Perigonblatt)**, **Verwachsungstyp (Perigonblatt)**, **Verwachsung (Perigonblatt)**
  - [ ] Perigonblatt Ausgabe:  "[Perigonblattanzahl] [Farbe/Gestalt (Perigonblatt)] `Perigonblätter,` [Verwachsungstyp (Perigonblatt)] [Verwachsung (Perigonblatt)]`.`"
  - [ ] Befüllung der Perigonblattfelder nur erlauben, wenn in Blütenhülle die Option `einfache Blütenhülle (Perigon)` ausgewählt ist, dabei dann Befüllung von Kelch- und Kronblattfeldern verbieten sowie umgekehrt bei allen anderen Optionen

- [ ] **Staubblattanzahl + Staubblattlänge + Farbe/Gestalt (Staubblatt)** im Admin-Interface gruppieren

- [ ] **Verwachsungstyp (Staubblatt)**: Dropdown, Optionen `Staubfadenröhre, verwachsen mit Kronblättern`

- [ ] **Verwachsungstyp (Staubblatt) + Verwachsungstypzusatz** im Admin-Interface gruppieren

- [ ] Staubblatt Ausgabe: "[Staubblattanzahl] [Staublattlänge] `cm lange,` [Farbe/Gestalt (Staubblatt)] `Staubblätter,` [Verwachsungstyp (Staubblatt)] [Verwachsungstypzusatz)]`.`"

**Comment by suehtomit** [comment]
- [x] Felder entsprechend Auflistung (26-32) benennen
