### ISSUE TITLE
Änderungen Kategorie "Zeigerzahl"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#44]
- [x] Umbenennen zu "Zeigerzahlen"

- [x] Anzeige einer Legende für „Light extra“ (Objekt der Zeigerzahlen) im Steckbrief unterhalb der Zeigerzahlen:
~ Zeiger für starken Wechsel
Zahl mit (?) = unsichere Einstufung

**Comment by chgad** [comment]
>  Umbenennen zu "Zeigerzahlen"
---> `verbose_name = _("Zeigerzahlen")`

> Anzeige einer Legende für „Light extra“ (Objekt der Zeigerzahlen) im Steckbrief unterhalb der Zeigerzahlen:
> ~ Zeiger für starken Wechsel
> Zahl mit (?) = unsichere Einstufung

---> Statisch in den Serializer

**Comment by suehtomit** [comment]
Vidyo-Meeting 29.03.2021 (@IH0815, @mgrethlein, @suehtomit ):

- [x] Neugestaltung des Models "ZeigerNumber" als "Indicators" (englischer Ausdruck: "Indicator values")
- [x] Deutscher Ausdruck "Zeigerwerte" -> Meta.verbose_name
- [x] Zahl der Lichtzahl kann in Klammen eingeschlossen sein, Bsp. `L(2)`, dient als Keimlingsangabe beim Bäumen,  ausgenommen sind `Lx` und `L?`
- [x] `(?)` als Zusatz zu jeder Zeigerzahl, ausgenommen Zahlen mit `x` und `?`, also nicht bei z. B. `Lx` oder `T?`
- [x] `~` als Zusatz nur bei der Feuchtezahl, ausgenommen `Fx` und `F?`
- [x] `=` als Zusatz nur bei der Feuchtezahl, ausgenommen `Fx` und `F?`
- [x] Alle Zusätze direkt hinter die jeweilige Zeigerzahl setzen, z. B. `L5 (?)`, `F4~ (?)`, `F11=`
- [x] Alle Zusätze als zusätzliche Checkbox-Felder hinter den entsprechenden Zeigerzahlen umsetzen
- [x] Legende als "read-only"-Feld, die automatisch nur mit den in den Zeigerwerten vorkommenden Zusätzen erstellt wird:
```
( ) Keimlingsangabe, (?) unsichere Einstufung, ~ Zeiger für starken Wechsel, = Überschwemmungszeiger
```
- [ ] Checkbox-Feld `not_specified`, das bei Aktivierung nur "Nicht angegeben" anzeigt und die Anzeige aller Zeigerwerte und der Legende unterdrückt

**Comment by suehtomit** [comment]
- [x] Anpassung der `NITROGEN_CHOICES`
```
N1: stickstoffärmste Standorte
N2: zwischen stickstoffärmste und -arme Standorte
N3: stickstoffarme häufiger als mäßig -reiche Standorte
N4: mäßig stickstoffreiche häufiger als -arme Standorte
N5: mäßig stickstoffreiche Standorte
N6: mäßig stickstoffreiche häufiger als -reiche Standorte
N7: stickstoffreiche haufiger als mäßig -reiche Standorte
N8: zwischen stickstoffreiche und übermäßig -reiche Standorte
N9: übermäßig stickstoffreiche Standorte
Nx – indifferentes Verhalten
N? – ungeklärtes Verhalten
```
