### ISSUE TITLE
Neue Kategorie "Wissenswertes"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#45]
_**Für die Reihenfolge und Anordnung im Admin-Interface bitte #40 beachten**_

### **Bestäubung**
- [x] Dropdown; Mehrfachauswahl durch STRG (Wie „Habitat“)
- [x] Einträge: 
„Selbstbestäubung; Wasserbestäubung; Windbestäubung; Insektenbestäubung“
- [x] Zusätzliches Textfeld, in dem bei "Insektenbestäubung" eine Liste von Insekten eingetragen werden kann, die in Klammern angezeigt wird. 100

### **Ausbreitung** 
- [x] Dropdown; Mehrfachauswahl durch STRG (Wie „Habitat“)
- [x] Einträge: 
„Menschenausbreitung; Selbstausbreitung; Stoß/Schüttelausbreitung; Verdauungsausbreitung; Versteck- u. Verlustausbreitung; Wasserausbreitung; Windausbreitung“

### **Detaillierte Merkmale**
- [x] Textfeld 200

### **Verwendung**
- [x] Textfeld (Markdown) 200

### **Trivia**
- [x] Textfeld (Markdown) 600

**Comment by chgad** [comment]
Notizen zur Impementierung.

Diese Felder kommen in das Model `Plant`.

Feldnamen für Felder:

Insektenbestäuber --> `insec_poll`
Bestäubung --> `pollination`
Ausbreitung --> `spread`
Detaillierte Merkmale --> `detail_traits`
Verwendung --> `usage`
Wissenswertes --> `fun_facts`
