### ISSUE TITLE
[DIVE] Neuer Eintrag "Taxonomie"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#46]
Dieser Eintrag wird gelistet als erster Eintrag unter "Allgemein" und wird aus der Einordnung im Stammbaum erstellt (ausgewählt durch „Steckbrief-Ebene“).

Beispiel zur Darstellung:
### Allgemein
**Taxonomie**
 -- |  --
----|----
Klasse | Magnoliopsida
Ordnung	|Ranunculales
Familie	|Ranunculaceae
Gattung	|_Anemone_
Art		|_Anemone nemorosa_

**Liste alternativer Trivialnamen**
...

**Comment by chgad** [comment]
> ### Allgemein
> **Taxonomie**
>  -- |  --
> ----|----
> Klasse | Magnoliopsida
> Ordnung	|Ranunculales
> Familie	|Ranunculaceae
> Gattung	|_Anemone_
> Art		|_Anemone nemorosa_
> 

Das wird sehr viel Platz einnehmen wenn wir es so darstellen. Warum nicht wie eine Ordnerstruktur darstellen ?

Format : <Klasse>/<Ordnung>/<Familie>/<Gattung>/<Art>
Besipiel:

Taxonomie : Magnoliopsida / Ranunculales / Ranunculaceae / _Anemone_ / _Anemone nemorosa_

@mgrethlein @sheepyhollow @IH0815 ?

Hat es auch eine Bewandniss warum Gattung und Art kursiv geschrieben sind?
Sind immer nur die letzten 4 Ebenen anzugeben?

**Comment by mgrethlein** [comment]
> Besipiel:
> 
> Taxonomie : Magnoliopsida / Ranunculales / Ranunculaceae / _Anemone_ / _Anemone nemorosa_
> 
Das sieht nach einer guten Lösung aus. Platzsparend und übersichtlich. Gefällt mir.


> 
> Hat es auch eine Bewandniss warum Gattung und Art kursiv geschrieben sind?
> Sind immer nur die letzten 4 Ebenen anzugeben?

Gattung und Art werden in der Biologie kursiv angegeben, das ist Teil der Nomenklatur. Wenn wir das nicht machen wird es spätestens Meike Piepenbring fordern.
Für die Klausur müssen die Studenten alles ab der Ordnung angeben, wir haben neben den Bedecktsamern (Magnoliopsida) allerdings auch einen Vertreter der Schachtelhalme (Equisetopsida), daher ergibt es Sinn alle 5 Ebenen darzustellen. Auf der oberen Ebene wäre auch die Unterscheidung zwischen Laub- und Nadelbäumen. Man kann es schlecht abschätzen, aber eventuell kommen Nadelbäume mal als teil der 100 Arten vor, dann wird das auch benötigt.
