### ISSUE TITLE
Pipe der Backend Eingabe zu Frontend Ausgabe

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#49]
Die in Issue #40 beschriebene neue Anordnung des Django Admin- Interface soll einerseits die Eingabe erleichtern, andererseits eine bessere Idee zur Darstellung im Frontend geben.

Die Eingegebenen Daten sollen vor der Ausgabe im Frontend in einzelne Zeilen zusammengefasst werden, ähnlich wie im Backend gruppiert. 
Die in Issue #40 angehängte Datei gliedert die Eingabe in 3 Ebenen:

1. Große Kategorien (Header, Kurzbeschreibung, Allgemeines, etc.) 
2. Unterkategorien (Blattmerkmale, Keimblattmerkmale, Blütenmerkmale, etc.) und 
3. einzelne Zeilen (Überblick, Anheftung, etc.)

Das folgende Dokument erläutert wie sich die unterste Ebene der Zeilen zusammensetzt, insbesondere welche Verbindungen zwischen den eingegebenen Parametern hinzugefügt werden müssen um einen sinnvollen Eintrag zu ergeben:
[Backend zu Frontend Parameter.docx](https://github.com/zentrumnawi/dive-backend/files/5817292/Backend.zu.Frontend.Parameter.docx)

**Comment by chgad** [comment]
@mgrethlein 

Ich brauche Erläuterungen zu :

"Als Bulletpoint in Kategorie Frucht"

und 

"Einzelne Bulletpoints in Kategorie Spross und Wurzel, Unterpunkt Sprossmerkmale"

Jede unter Kategorie wird dann automatisch "ausklappbar" und beim erstmaligen auswählen eingeklappt sein.

P.S.: Was zur Hölle habt ihr mir da aufgedrückt :laughing:

**Comment by mgrethlein** [comment]
"Als Bulletpoint in Kategorie _____"  bedeutet, dass alle aufgeführten Backend Parameter zu einzelnen Zeilen im Frontend zusammengefasst werden. 
"Einzelne Bulletpoints in Kategorie Spross und Wurzel, Unterpunkt Sprossmerkmale" bedeutet, dass die 3 Backend Parameter "Wuchsorientierung, Erscheinung, Dickfleischig" zu einer Zeile zusammengefasst werden. Die Zeile gehört in die Unterkategorie "Sprossmerkmale" der Kategorie "Spross und Wurzel"


Die Darstellung im Frontend stellen wir uns dann etw so vor:


![Steckbrief Layout 2 0 kommentiert](https://user-images.githubusercontent.com/65898728/107433648-ed0fd100-6b29-11eb-8453-af8c2f3633c9.png)

**Comment by sheepyhollow** [comment]
Wir müssten im Frontend auch noch Unterkategorien einfügen, oder?
Wieviele Unterkategorien gibt es denn je großer Kategorie? Wenn nur Spross & Wurzel Unterkategorien haben, könnte man die auch auseinandernehmen und die Unterkategorien einsparen. Im Prinzip ist es uns aber egal, denke ich.

**Comment by chgad** [comment]
> Im Prinzip ist es uns aber egal, denke ich.

Soll es die nun geben oder nicht?

**Comment by mgrethlein** [comment]
> Wieviele Unterkategorien gibt es denn je großer Kategorie? 

Blatt besitzt die Unterkategorien _Blattmerkmale_ und _Keimblattmerkmale_, wobei man letztes eventuell einsparen kann, da es nur einen Punkt besitzt.
Die Blüte hat die Unterkategorien _Blütenmerkmale_ und je eine für die _Sonderformen_ (Poales, Asteraceae und Lamiaceae).
Spross und Wurzel haben eben _Sprossmerkmale_ und _Wurzeln und Unterirdische Pflanzenorgane_.
Schließlich ist Wissenswertes aufgeteilt in die Unterkategorien _Bestäubung und Ausbreitung_, _Verwendung_ und _Wissenswertes_. Über die Benennung der Kategorie müssen wir eventuell nochmal nachdenken.
