### ISSUE TITLE
Textumsetzung & weitere Änderungen der Kategorie "Allgemeines"

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#56]
Als eine Ergänzung zu Issue #49 bekommt auch die Kategorie Allgemeines einen Textblock. Da die Umsetzung sich hier schwieriger Gestaltet werden die einzelnen Änderungen detailiert aufgelistet.

### **Änderungen in Feldern:**
**Feld "Ausbreitungsform"**
- [x] Eintrag "Samenpflanze" löschen, ersetzen durch die Eintrage "Nacktsamer" und "Bedecktsamer"

**Felder "Wuchsform" & "Lebensform" überarbeiten:**
- [x] Von "Wuchsform" zu "Lebensform" verschieben: Geophyt, Helophyt, Hydrophyt
- [x] Bei "Wuchsform" ergänzen: Kraut, Scheinstrauch, Staudenstrauch

**Feld "Habitat" überarbeiten:**
Alt | Neu
--|--
Schlammfluren | 
Röhrichte | Röhrichten
Säume | Säumen
Staudenfluren | 
Grünland u. Zwergstrauchheiden | Grünland
Grünland u. Zwergstrauchheiden | Zwergstrauchheiden 
Ruderalvegetation | 
Äcker | Äckern
Weinberge |  Weinbergen
Intensivgrünland | 
Parks |
Gärten |
Trittpflanzengesellschaften |
Felsbiotope | Felsbiotopen 
Auenwälder | Auenwäldern
Gebüsche | Gebüschen
Extensivgrünland oder nat.   Rasen | Extensivgrünland 
Extensivgrünland oder nat.   Rasen | natürlichem Rasen
Wälder | Wäldern
Ufer | Ufern

### Grammatikalische Anpassung zur Umsetzung
**1. Trennung der Begriffe zur Anzeige bei Mehfachauswahl**
- [x] Bei Auswahl von zwei Begriffen welche nicht durch ein "bis" verbunden werden, diese durch ein "und" verbinden.
- [x] Bei Auswahl von 3 oder mehr Begriffen diese durch Komma trennen, die letzten beiden durch ein "und" verbinden.

Außerhalb der Kategorie "Allgemeines", Feld "Habitat", betrifft das die Felder "Bestäubung" und "Ausbreitung" in der Kategorie "Wissenswertes"

**2. Ergänzen der Artikel**
Um die ausgegebenen Texte grammatikalisch korrekt darzustellen, müssen die korrekten Präpositionen und Artikel hinzugefügt werden. 

- [x] Hierzu muss ein Feld zur Auswahl der Artikel "Der, Die, Das" vor dem Feld "Trivialname ergänzt werden.

Diese Präpositionen (vgl. **Der Text zur Ausgabe**, P1-4) ergeben sich wie folgt:

- [x] P1-3 werden durch die Auswahl in Feld "Ausbreitungsform" definiert:

--| P1 | P2 | P3
--|--|--|--
Nackt/Bedecktsamer | einen | -en | welcher
Sporenpflanze | eine | -e | welche

- [x] P4 umfasst die Präpositionen _in/ an/ auf_ und wird Habitatabhängig definiert. Wenn mehrere Begriffe mit gleicher Präposition aufeinander Folgen, darf nur die erste Instanz der Präposition angezeigt werden.

--| Habitat
--|--
an | Säumen, Ufern
in | Schlammfluren, Röhrichten, Staudenfluren, Zwergstrauchheiden, Ruderalvegetation, Weinbergen, Parks, Gärten, trittpflanzengesellschaften, Felsbiotopen, Auenwäldern, Gebüschen, Wäldern
auf | Grünland, Äckern, Intensivgrünland, Extensivgrünland, natürlichem Rasen

**Beispiele für die Kombination der Präpositionen und Kommatrennung:**
Bsp 1: welche in Wäldern, an Waldrändern und auf Wiesen vokommt.
Bsp 2: welche in Wäldern, Gärten, Weinbergen und an Ufern vorkommt.

### Der Text zur Ausgabe
Die Grundstruktur zur Darstellung ist wie folgt:

[**Artikelfeld**] [**Trivialname**] ([**Art**]), auch [**Liste AlternativerTrivialnamen**] genannt, ist ein [**Wuchsform**] mit einer Wuchshöhe von [**Wuchshöhe**]. Es handelt sich um _P1: eine/n_ [**Interaktion**] _P2: -e/en_ [**Ausbreitungsform**], _P3: welche/r_ auf [Untergrund] Untergrund _P4: in/an/ auf_ [**Habitat**] vorkommt. Bei [**Art modifiziert**] handelt es sich um einen [**Lebensform**]; die Pflanze gilt als [**Status**].

Umgesetzt ergibt sich das folgende Bild:
**Das Buschwindröschen (_Anemone nemorosa_)**, auch **Buschwindröschen**, ist ein **Kraut** mit einer Wuchshöhe von **0,2-0,3m**. Es handelt sich um _einen_ **nicht-parasitische**_en_ **Bedecktsamer**, _welcher_ auf **feuchtem** Untergrund _in_ **Waldgebieten, auf Wiesen und in Auenwäldernvorkommt**. Bei **_A. nemorosa_** handelt es sich um einen **Geophyt**; die Pflanze gilt als **einheimisch**.

- [x] Das Feld "Art modifiziert" ergibt sich auf dem Artnamen. Hierbei wird der erste Buchstabe beibehalten und alles bis zum Leerzeichen durch einen Punkt ersetzt.
_Anemone neomorsa_ -> _A. nemorosa_
- [x] Der Satzbaustein "auf [Untergrund] Untergrund" darf nur angezeigt werden, wenn [Untergrund] spezifiziert ist.

**Comment by IH0815** [comment]
- [ ] Hinzufügen Feld "Weitere Merkmale" als Textfeld, mit Toolitpp: "z. B. Geruch". Einbau hinter [Status] wie folgt: _...die Pflanze gilt als [Status]. [Weitere Merkmale]._

**Comment by suehtomit** [comment]
Habitat-Optionen:
```
"Schlammflure"
"Röhrichte"
"Säume"
"Staudenflure"
"Grünland"
"Zwergstrauchheiden"
"Ruderalvegetationen"
"Äcker"
"Weinberge"
"Intensivgrünland"
"Parks"
"Gärten"
"Trittpflanzengesellschaften"
"Felsbiotope"
"Auenwälder"
"Gebüsche"
"Gerölle"
"Extensivgrünland"
"natürliche Rasen"
"Wälder"
"Ufer"
"Weiden"
"Wiesen"
"Hecken"
"Gräben"
"Weg-/Straßenränder"
"Bahndämme"
"Bäche"
"Schutt"
"Bruchwälder"
"Quellen"
"Schläge"
```

**Comment by IH0815** [comment]
Die Habitatsliste wurde jetzt noch mal überarbeitet. Die oben angegebenen Spezifikationen, d. h. die Angabe mit den Präpositionen usw. bleiben bestehen. Einzig der Listeninhalt der Habitatsliste wird länger und es kommt noch ein Dropdown-Textfeld (Mehrfachauswahl) hinzu. Außerdem müsste die Untergrund-Liste um ein paar Begriffe ergänzt werden. 

- [ ] Habitatsliste
- [ ] Ruderalstellenliste
- [ ] Untergrund-Liste

Die Liste der Habitate usw. ist in der angehängten Excel-Datei zu finden. Bitte die vorhandenen Listen mit den neuen Listen ersetzen. 

**Der Satz**

Die ausgegebenen Sätze werden wie folgt gebildet:

**[Artikelfeld] [Trivialname]** (**[Art]**), auch **[Liste AlternativerTrivialnamen]**, ist ein **[Wuchsform]** mit einer Wuchshöhe von **[Wuchshöhe]**. Es handelt sich um P1: _eine/n_ **[Interaktion]** P2: -_e/en_ **[Ausbreitungsform]**, P3: _welche/r_ auf **[Untergrund]** Untergrund P4: _in/an/ auf_ **[Habitat]**, sowie Ruderalstandorten (**[Ruderalstandorte]**) vorkommt. Bei **[Art modifiziert]** handelt es sich um einen **[Lebensform]**; die Pflanze gilt als **[Status]**.

- Der Satzteil "sowie Ruderalstandorten ([Ruderalstandorte])" wird nur dann ausgegeben, wenn im Feld "Ruderalstandorte" etwas angewählt ist. 
- Das ist derselbe Satz wie oben, lediglich der Teil mit den Ruderalstandorten wurde ergänzt. 
- Für die Ruderalstellen sind keine Präpositionen oder verbindende "und"s notwendig, da sich die Begriffe in der Klammer befinden. 

Der Beispielsatz: _Das Buschwindröschen (Anemone nemorosa), auch Buschwindröschen, ist ein Kraut mit einer Wuchshöhe von 0,2-0,3m. Es handelt sich um einen nicht-parasitischeen Bedecktsamer, welcher auf feuchtem Untergrund in Waldgebieten, auf Wiesen und in Auenwäldern, sowie Ruderalstandorten (Böschungen, Dämme, Kiesgruben) vorkommt. Bei A. nemorosa handelt es sich um einen Geophyt; die Pflanze gilt als einheimisch._

**Die Listen**
In der Excel-Liste sind 3 Listen zu finden.
- Die neue Habitatsliste mit den zugehörigen Präpositionen
- Die Liste der Ruderalstellen ohne Präpositionen
- Die Liste der Untergründe, ebenfalls ohne Präpositionen


- [ ] Bitte alle Begriffe in den neuen Listen alphabetisch ordnen


[Habitate.xlsx](https://github.com/zentrumnawi/dive-backend/files/6872198/Habitate.xlsx)

**Comment by mgrethlein** [comment]
Bitte um eine Ergänzung im Dropdown Menü "Wuchsform"

- [ ] Eintrag "Spreizklimmer" hinzufügen
