### ISSUE TITLE
Korrekturen & Nachträge zum Blattmodel (#39)

### ISSUE THREAD

**Issue by mgrethlein** [zentrumnawi/dive-backend#61]
In den Feldern Spreiten-/Blättchenrand (bzw. Nebenblattrand & Blattoberfläche:
- [x] Rauh ändern zu rau

Um z.B. Ahorn abbilden zu können bekommen einfach Blätter einen Zusatz: 
- [x] Kopieren der Felder "Einschnittanzahl" & "Einschnitttiefe"der zusg. Blätter
- [x] Einschnittiefe benötigt nur Auswahl "ganz/ungeteilt, gelappt, gespalten, geteilt, geschnitten", Rest wird verworfen

**Comment by mgrethlein** [comment]
**Um konsistent in der Benennung zu bleiben ein Nachtrag:**
- [ ] Spreitengestalt (unterteiltes Blatt) umbenennen zu Spreitengestalt (zsg. Blatt) und 
- [ ] Spreitengestalt (ungeteiltes Blatt) umbenennen zu Spreitengestalt (einf. Blatt) 

**Ergänzen von Auswahlmöglichkeiten in Dropdown /Multiple choice Feldern**
- [ ] Blattoberfläche:
* glänzend

**Ergänzen von Feldern**
- [ ] Unterkategorie Blattmerkmale, noch vor [Blattnerven]
* Textfeld [Blattfarbe]; Im Satz angezeigt vor [Blattnerven] (dunkel grüne, steifennervige, einfache, ...)

**Sonstiges:**
- [ ] Tooltipp des Feldes "Besondere Merkmale" entfernen, erfüllt in der neuen Struktur keinen Sinn

**Comment by suehtomit** [comment]
```
    ALTER BEGRIFF                             NEUER BEGRIFF                   |  ALTE VARIABLE           NEUE VARIABLE
------------------------------------------------------------------------------------------------------------------------------
 1. + Blattfarbe                                                              |  color
 
 2. Blattanzahl (zusg. Blätter)           ->  Blattanzahl (zusg. Blatt)       |  leaf_comp_num
 3. Spreitengestalt (unterteiltes Blatt)  ->  Spreitengestalt (zusg. Blatt)   |  blade_subdiv_shape  ->  leaf_comp_blade_shape
 4. Einschnittanzahl                      ->  Einschnittanzahl (zusg. Blatt)  |  incision_num        ->  leaf_comp_incision_num
 5. Einschnitttiefe                       ->  Einschnitttiefe (zusg. Blatt)   |  incision_depth      ->  leaf_comp_incision_depth

 6. Blattanzahl (einf. Blätter)           ->  Blattanzahl (einf. Blatt)       |  leaf_simple_num
 7. Spreitengestalt (ungeteiltes Blatt)   ->  Spreitengestalt (einf. Blatt)   |  blade_undiv_shape   ->  leaf_simple_blade_shape
 8. + Einschnittanzahl (einf. Blatt)                                          |  leaf_simple_incision_num
 9. + Einschnitttiefe (einf. Blatt)                                           |  leaf_simple_incision_depth
```

**Comment by suehtomit** [comment]
- [x] Zusg. Blatt: Blattanzahl, Spreitengestalt, Einschnittanzahl, Einschnitttiefe in Admin-Interface in einer Zeile
- [x] Einf. Blatt: Blattanzahl, Spreitengestalt, Einschnittanzahl, Einschnitttiefe in Admin-Interface in einer Zeile
- [x] Ausgabesatz "Überblick" anpassen
- [x] Ausgabesatz "Blattfläche – zusammengesetztes Blatt" anpassen
- [x] Ausgabesatz "Blattfläche – einfaches Blatt" anpassen
- [x] Alle anderen Ausgabesätze des LeafSerializers überarbeiten
