### ISSUE TITLE
Korrekturen & Nachträge zum Frucht-Modell

### ISSUE THREAD

**Issue by IH0815** [zentrumnawi/dive-backend#62]
- [x] Ergänzung um das Textfeld "Farbe" unter Frucht (Samen Aussehen), einfügen als: 
**[Farbe]** [Samenzahl] [Form der Samen] Samen, [Beflügelung Besonderheit] [Beflügelung]

**Comment by suehtomit** [comment]
Statt einem ergänzenden Textfeld wird das bestehende Textfeld "Samenform" in "Farbe/Form (Samen)" umbenannt, analog zu Feldern im Blossom-Model, `seed_form  ->  seed_color_form`. Die Ausgabesatzstruktur bleibt dadurch unverändert: [Samenanzahl] [**Farbe/Form (Samen)**] Samen, [Beflügelung] [Beflügelung (Besonderheit)]

**Comment by suehtomit** [comment]
Statt einem ergänzenden Textfeld wird das bestehende Textfeld "Samenform" in "Farbe/Form (Samen)" umbenannt, analog zu Feldern im Blossom-Model, `seed_form  ->  seed_color_form`. Die Ausgabesatzstruktur bleibt dadurch unverändert:
"[Samenanzahl] [**Farbe/Form (Samen)**] Samen, [Beflügelung] [Beflügelung (Besonderheit)]."
