### ISSUE TITLE
Korrekturen & Nachträge zum Spross- und Wurzel-Modell

### ISSUE THREAD

**Issue by IH0815** [zentrumnawi/dive-backend#63]
- [x] Hinzufügen eines Feldes "Füllung" (Choicefield) mit den Auswahlmöglichkeiten "hohl" und "markig" bzw. "none". Einfügen hinter den Satz unter _Sprossmorphologie_ wie folgt: [Querschnitt]er Querschnitt, mit [Sprossoberfläche]er Oberfläche. **Der Spross ist [Füllung].** 

- [x] Fehler beheben: Im Mehrfachwählfeld "Querschnitt" gibt es die Einträge "kantig" und "kantig gefurcht/scharfkantig". Wählt man _einen_ der beiden Einträge aus, so wird automatisch der andere Eintrag ebenfalls ausgewählt. Im Frontend immer ausgegeben als: "kantig gefurcht/scharfkantig".

**Comment by suehtomit** [comment]
- [x] Zusätzliches Feld "Füllung" als "Mark"
- [x] Ausgabesatz "_Sprossmorphologie_": "[Wuchsorientierung]er, [Erscheinung]er, [Dickfleischigkeit]er, **[Mark]er** Spross; [Querschnitt]er Querschnitt mit [Sprossoberfläche]er Oberfläche."
