### ISSUE TITLE
Ergänzung Blüten-Model

### ISSUE THREAD

**Issue by suehtomit** [zentrumnawi/dive-backend#66]
Perigonblatt (aus #43 übriggebliegen):
- [x] Neue Kategorie "Perigonblatt" erstellen:
  - [x] Felder analog zu Kelch-/Kronblatt: **Perigonblattanzahl**, **Farbe/Gestalt (Perigonblatt)**, **Verwachsungstyp (Perigonblatt)**, **Verwachsung (Perigonblatt)**
  - [x] Perigonblatt Ausgabe:  "[Perigonblattanzahl] [Farbe/Gestalt (Perigonblatt)] `Perigonblätter,` [Verwachsungstyp (Perigonblatt)] [Verwachsung (Perigonblatt)]`.`"
  - [x] ~~Befüllung der Perigonblattfelder nur erlauben, wenn in Blütenhülle die Option `einfache Blütenhülle (Perigon)` ausgewählt ist, dabei dann Befüllung von Kelch- und Kronblattfeldern verbieten sowie umgekehrt bei allen anderen Optionen~~

**Comment by IH0815** [comment]
Bitte noch einen Begriff in die Dropdownliste "Blütenstandstyp" einfügen, nähmlich "Scheinähre". 

- [ ] Scheinähre erledigt

**Comment by IH0815** [comment]
**Überblick:** 

- [ ] Anzahl Fruchtknoten
- [ ] Anzahl Griffel
- [ ] Textfeld in Blütenkategorie

------------------------------------------------------

**Anzahl von Fruchtknoten & Griffeln**

Bitte noch zwei Anzahl-Felder hinzufügen in: Blüte (Fruchtblätter). 

Momentan sieht der Satz so aus: 

[Fruchtblätter Anzahl] [Verwachsungstyp Fruchtbl.] **verwachsene Fruchtblätter,** [Ständigkeit des Fruchtknotens]**er Fruchtknoten,** [Ständigkeit des Griffels]**er Griffel mit** [Narben pro Griffel] **Narben;** [Griffelpolster]. 

Hinzugefügt werden sollen eine Anzahl-Angabe für die Fruchtknoten und eine für die Griffel, sodass der Satz dann folgendermaßen aussieht: 

[Fruchtblätter Anzahl] [Verwachsungstyp Fruchtbl.] **verwachsene Fruchtblätter,** _[Anzahl Fruchtknoten]_ [Ständigkeit des Fruchtknotens]**er Fruchtknoten,** _[Anzahl Griffel]_ [Ständigkeit des Griffels]**er Griffel mit** [Narben pro Griffel] **Narben;** [Griffelpolster]. 

Die Anzahlfelder sind die üblichen zwei Zahlenfelder mit einer Auswahlmöglichkeit von 1 bis 10, mit 11 = unendlich. (Je 2 Felder von 1-11, sodass Range-Angaben möglich sind.) 

Außerdem wäre dann noch eine grammatikalische Anpassung notwendig: ist der Zahlenwert 1 eingetragen, so wird das nachfolgende Feld [Ständigkeit] mit einem "er" versehen, ist die Zahl größer als 1, ist es nur ein "e". 

**Beispiele:**
_3 Fruchtblätter, 1 oberständiger Fruchtknoten, 5 seitenständige Griffel mit 3 Narben. 
3 Fruchtblätter, 2 oberständige Fruchtknoten, 1 seitenständiger Griffel mit 3 Narben.
3 Fruchtblätter, 1-2 oberständige Fruchtknoten, 1-10 seitenständige Griffel mit 3 Narben._

-------------------------------------------------------

**Textfeld**

Bitte noch ganz ans Ende des Blütenmodells ein freies Textfeld hinzufügen. Dieses soll nicht zugehörig zur Fruchtblattkategorie, sondern für sich gestellt sein.

**Comment by suehtomit** [comment]
#91
