### ISSUE TITLE
Contact/Feedbacl

### ISSUE THREAD

**Issue by chgad** [zentrumnawi/dive-backend#74]
Für das Feddback über den von solid implementierten `contact/` Endpoint muss Mailgun implementiert werden.

Als Richtlinie gilt das alte [GeoMat Backend](https://github.com/GeoMatDigital/django-geomat/blob/develop/config/settings/production.py#L70) .

Wir besitzen noch einen alten Mailgun Key der in dokku apps wie `geomat-backend-staging`gespeichert ist.

Dieser kann prinzipiell verwendet werden (solange er noch funktioniert); der Account der diesen Verwaltet kenne ich nicht.
Im Zweifel muss ein neuer SMTP-Provider her (Mailgun verlagnt Kreditkarten Infos auch für kostenlose 3.000 mails/Monat accounts).

**Comment by sheepyhollow** [comment]
Hm... ich habe einen Mailjet-Account, der funktioniert. Zu Mailgun habe ich keine Unterlagen bei mir gefunden.
